### ISSUE TITLE
Could you provide some information about the reproduction of MAE-B in 100ep pretraining ?

### ISSUE THREAD

**Issue by HuangChiEn** [UCSC-VLAA/DMAE#4]
Thanks for releasing this amazing work. 
We want to know some detail about the reproduction of MAE-B in 100ep if you don't mind. Since the [repository](https://github.com/facebookresearch/mae) you'll refer do not provide the configuration for pretraining MAE of ViTB version. 

We wonder **what configuration (or where to get it)** did you'll use to reproduce the 100ep finetuneing results of imageNet-1K based on **100-ep pretraining** ?

Any suggestion will be appreciated !!

**Comment by cihangxie** [comment]
Thanks for your interest in our work. The code is released now.
